services:
  certificate-authority-service:
    container_name: ${APP_CONTAINER_NAME}
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    restart: always
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ${DESTINATION_FOLDER}/var/app:/app
    ports:
      - ${APP_PORT}:8080
    command: cd /app && dotnet AktivCA.Web.dll
  certificate-authority-service-db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:17.2
    environment:
      POSTGRES_PASSWORD: ${DB_PSWD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - ${DESTINATION_FOLDER}/var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432